// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7hrScLgXZKC4TLoJOTJxpHOA6CTDDFc',
    appId: '1:554265067111:web:528718000f200725379ec2',
    messagingSenderId: '554265067111',
    projectId: 'podsy-bd462',
    authDomain: 'podsy-bd462.firebaseapp.com',
    storageBucket: 'podsy-bd462.firebasestorage.app',
    measurementId: 'G-75HKFYJ56G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoi-5H3UwPTQE0CdijJQhQpnfd-AFeeMc',
    appId: '1:554265067111:android:ff2209b087817f07379ec2',
    messagingSenderId: '554265067111',
    projectId: 'podsy-bd462',
    storageBucket: 'podsy-bd462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcICgLrg1NzIwZsqjel-irWh3-f3dm8w4',
    appId: '1:554265067111:ios:fc9919b857d68f97379ec2',
    messagingSenderId: '554265067111',
    projectId: 'podsy-bd462',
    storageBucket: 'podsy-bd462.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcICgLrg1NzIwZsqjel-irWh3-f3dm8w4',
    appId: '1:554265067111:ios:fc9919b857d68f97379ec2',
    messagingSenderId: '554265067111',
    projectId: 'podsy-bd462',
    storageBucket: 'podsy-bd462.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm7hrScLgXZKC4TLoJOTJxpHOA6CTDDFc',
    appId: '1:554265067111:web:663db3243587dee4379ec2',
    messagingSenderId: '554265067111',
    projectId: 'podsy-bd462',
    authDomain: 'podsy-bd462.firebaseapp.com',
    storageBucket: 'podsy-bd462.firebasestorage.app',
    measurementId: 'G-7EV43K9L8G',
  );
}
